/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_mrpan_gaosimohu_BitmapUtils */

#ifndef _Included_com_example_mrpan_gaosimohu_BitmapUtils
#define _Included_com_example_mrpan_gaosimohu_BitmapUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_mrpan_gaosimohu_BitmapUtils
 * Method:    initCBlur1
 * Signature: ([IIII)V
 */
JNIEXPORT void JNICALL Java_com_example_mrpan_gaosimohu_BitmapUtils_initCBlur1
  (JNIEnv *, jobject, jintArray, jint, jint, jint);

/*
 * Class:     com_example_mrpan_gaosimohu_BitmapUtils
 * Method:    initCBlur2
 * Signature: ([IIII)V
 */
JNIEXPORT void JNICALL Java_com_example_mrpan_gaosimohu_BitmapUtils_initCBlur2
  (JNIEnv *, jobject, jintArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
